language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get -y install jq
addons:
  chrome: stable
script:
  - echo "headless=true" > chrome.properties
  - mvn clean verify -Ddriver=chrome -Dchrome.capabilities.path="../../../chrome.properties"
after_failure:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
  - echo "Build was failed"
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
  - echo "Build was successful"
after_script:
  - ls -la
  - ls -la /home/travis/.m2/repository/webdriver/chromedriver/linux64/76.0.3809.126/chromedriver
  - google-chrome-stable --version
  - npm install -g allure-commandline
  - allure --version
  - total=""; for r in $(ls -d jdi*/); do allureDir="${r}allure-results"; if [ -d "$allureDir" ] ; then  echo "Results found for $r"; total="${total} ${allureDir}"; else echo "RESULTS NOT FOUND FOR ${r}"; fi ; done ; echo $total; allure generate --clean $total
  - du -d 1 -h ./
  - npm install -g netlify-cli
  - travis_wait 30 netlify deploy --dir allure-report --json
  - echo "Script finished"